# This is an autogenerated file. Do not edit

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)

 
set(KMEANS_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE STRING "" FORCE)
mark_as_advanced(KMEANS_INCLUDE_DIRS)
   

find_library(KMEANS_DEBUG_LIBRARY kmeans_d)
find_library(KMEANS_LIBRARY       kmeans)


if (KMEANS_DEBUG_LIBRARY)
  set(KMEANS_LIBRARIES optimized;${KMEANS_LIBRARY};debug;${KMEANS_DEBUG_LIBRARY})
else()
  set(KMEANS_LIBRARIES ${KMEANS_LIBRARY})
endif()

set(KMEANS_LIBRARIES ${KMEANS_LIBRARIES} CACHE INTERNAL "" FORCE)
 
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(KMEANS DEFAULT_MSG
  KMEANS_LIBRARIES
  KMEANS_INCLUDE_DIRS
)
set(KMEANS_PACKAGE_FOUND ${KMEANS_FOUND} CACHE INTERNAL "" FORCE)
 
set(KMEANS_DEPENDS "" CACHE INTERNAL "" FORCE)
 