# Autogenerated file.
# Do not edit.
# Do not change location.
 
set(KMEANS_INCLUDE_DIRS "/home/sami/cassiopee/worktree/stip/libKmeans;/home/sami/cassiopee/worktree/stip/libKmeans/." CACHE INTERNAL "" FORCE)
 
set(KMEANS_LIBRARIES "general;/home/sami/cassiopee/worktree/stip/build-nao-toolchain/sdk/lib/libkmeans.so" CACHE INTERNAL "" FORCE)
 
set(KMEANS_TARGET "kmeans" CACHE INTERNAL "" FORCE)

set(KMEANS_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(KMEANS_DEPENDS "" CACHE INTERNAL "" FORCE)
 