/**
 * @author Emilie Wirbel
 *
 * \section Description
 * This file was generated by Aldebaran Robotics ModuleGenerator
 */

#include <signal.h>
#include <boost/shared_ptr.hpp>
#include <alcommon/albroker.h>
#include <alcommon/almodule.h>
#include <alcommon/albrokermanager.h>
#include <alcommon/altoolsmain.h>
#include "stip.h"


#ifdef STIP_IS_REMOTE
# define ALCALL
#else
# ifdef _WIN32
#  define ALCALL __declspec(dllexport)
# else
#define ALCALL
#endif
#endif

/**
 First of all you need to create a broker,
 then you must add your new broker into the NAOqi’s broker manager.
 Then you can create your custom module and link it
 with the new broker you have just created.
  */

extern "C"
{           //entry point
  ALCALL int _createModule(boost::shared_ptr<AL::ALBroker> pBroker)
  {
    AL::ALBrokerManager::setInstance(pBroker->fBrokerManager.lock());
    AL::ALBrokerManager::getInstance()->addBroker(pBroker);
    AL::ALModule::createModule<Stip>( pBroker, "Stip" );

    return 0;
  }
        //exit point
  ALCALL int _closeModule()
  {
    return 0;
  }
}

#ifdef STIP_IS_REMOTE
  int main(int argc, char *argv[])
  {
    // pointer to createModule
    TMainType sig;
    sig = &_createModule;
    // call main
    ALTools::mainFunction("stip", argc, argv, sig);
  }
#endif

